### ISSUE TITLE
YUI3 Core package was not found; npm install yui3-core

### ISSUE THREAD

**Issue by thmundal** [davglass/nodejs-yui3#22]
I get this error from trying to access require("yui3").YUI on my windows installation of nodejs, and yui3-core is present in the node_modules subdirectory of yui3. I also tried to npm install yui3-core without any change.

Error: YUI3 Core package was not found; npm install yui3-core
    at D:\node.js\node_modules\yui3\lib\node-yui3.js:299:15
    at D:\node.js\node_modules\yui3\lib\node-yui3.js:13:15
    at Object.YUI (D:\node.js\node_modules\yui3\lib\node-yui3.js:24:15)
    at repl:1:5
    at REPLServer.eval (repl.js:82:21)
    at Interface.<anonymous> (repl.js:182:12)
    at Interface.emit (events.js:67:17)
    at Interface._onLine (readline.js:162:10)
    at Interface._normalWrite (readline.js:236:10)
    at Socket.<anonymous> (readline.js:75:12)

**Comment by davglass** [comment]
The old `yui3` package is not supported on Windows. You should install the new `yui` that contains our 3.5.0pr1 release which introduces native YUI use on Node.js as well as Windows support.

Note that there is no IO or DOM available in the `yui` package, it's just the base system with simple `Y.Get` support for JSONP and YQL use. IO will be coming in the PR2 release as well as examples on how to use a DOM with it.
