### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by japj** [davglass/nodejs-yui3#26]
Hi,

I tried installing mojito on windows (node 0.6.18 and got the following error:

npm ERR! Not compatible with your operating system or architecture: yui3@0.7.12
npm ERR! Valid OS:    darwin,linux
npm ERR! Valid Arch:  any
npm ERR! Actual OS:   win32
npm ERR! Actual Arch: ia32

I read somewhere that there were issues with building mojito C++ (dependant) addons on windows .

node-gyp (a replacement for node-waf) seems to work ok for me for other addons and I believe it is the preferred way of building C++ addons for nodejs.

Let me know if I can help with getting yui3 working on windows

**Comment by davglass** [comment]
This module is not the official module, the `yui` module is and the `mojito` team is working to incorporate the latest version into their system.

**Comment by japj** [comment]
ok, sorry. Is the npm information still correct then?

According to http://search.npmjs.org/#/yui3 this repository is the one where issues should be submitted.

**Comment by davglass** [comment]
http://search.npmjs.org/#/yui

The `yui` package is the official one, this one was a prototype that Mojito was built on. They are in the process of upgrading to the official `yui` package that works on Windows (because it doesn't include JSDOM)
